CREATE CONSTRAINT mystery_id IF NOT EXISTS
FOR (m:Mystery) REQUIRE m.id IS UNIQUE;

CREATE CONSTRAINT location_id IF NOT EXISTS
FOR (l:Location) REQUIRE l.id IS UNIQUE;

CREATE CONSTRAINT time_period_id IF NOT EXISTS
FOR (tp:TimePeriod) REQUIRE tp.id IS UNIQUE;

CREATE CONSTRAINT category_id IF NOT EXISTS
FOR (c:Category) REQUIRE c.id IS UNIQUE;