import type { Metadata } from 'next';
import { League_Spartan, Roboto } from 'next/font/google';
import './globals.css';
import Footer from '../components/Footer';
import Header from '../components/Header';

const leagueSpartan = League_Spartan({
  variable: '--font-league-spartan',
  subsets: ['latin'],
});

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${leagueSpartan.variable} ${roboto.variable} antialiased`}
      >
        <Header />
        <main className={'flex flex-col min-h-screen dark:bg-dark-gray'}>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
